# Site settings
title: Kat's Home
email: katrinaxxy@gmail.com
description: ""
baseurl: ""
url: "http://katrina.im"

# Build settings
markdown: kramdown
permalink: pretty

# Pages
paginate: 5
paginate_path: ":num"
